[package]
name = "coil_core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version = "0.25.1", features = ["extension-module"]}
tokio = { version = "1.47.0", features = ["full"] }
once_cell = "1.21.3"